AgenceVoyageWeb/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',include('app1.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/urls.py
from django.urls import path
from . import views
# from django.contrib.auth import views as auth_views
from .views import reserve,download_pdf

urlpatterns = [
    path('test/', views.test , name='test'),
    path('', views.home , name='home'),
    path('page2/', views.test2 , name='test2'),
    path('login/', views.loginPage , name='login'),
    path('register/', views.register , name='register'),
    path('registerAdmin/', views.registerAdmin , name='registerAdmin'),
    path('client/', views.ClientPage , name='client'),
    path('ClientSettings/', views.ClientSettings , name='ClientSettings'),
    path('AdminPage/', views.AdminPage , name='AdminPage'),
    path('logout/', views.logoutUser , name='logout'),
    path('voyages/', views.voyages , name='voyages'),
    path('addvoyage/', views.createvoyage , name='addvoyage'),
    path('updatevoyage/<str:pk>/', views.updatevoyage, name='updatevoyage'),
    path('deletevoyage/<str:pk>/', views.deletevoyage, name='deletevoyage'),
    path('categories/', views.categories , name='categories'),
    path('addcategorie/', views.addcategorie , name='addcategorie'),
    path('updatecategorie/<str:pk>/', views.updatecategorie, name='updatecategorie'),
    path('deletecategorie/<str:pk>/', views.deletecategorie, name='deletecategorie'),
    path('reservationclient/<str:pk>/', views.reservationclient, name='reservationclient'),
    path('reserve/<str:pk>/', views.reserve, name='reserve'),
    path('hotels/', views.hotels , name='hotels'),
    path('addhotel/', views.addhotel , name='addhotel'),
    path('updatehotel/<str:pk>/', views.updatehotel, name='updatehotel'),
    path('deletehotel/<str:pk>/', views.deletehotel, name='deletehotel'),
    path('vols/', views.vols , name='vols'),
    path('addvol/', views.addvol , name='addvol'),
    path('updatevol/<str:pk>/', views.updatevol, name='updatevol'),
    path('deletevol/<str:pk>/', views.deletevol, name='deletevol'),
    path('admins/', views.admins , name='admins'),
    path('detailsvoyage/<str:pk>/', views.detailsvoyage, name='detailsvoyage'),
    path('categorievoyage/<str:pk>/', views.categorievoyage, name='categorievoyage'),

    # path('reset_password/',auth_views.PasswordResetView.as_view(),name="reset_password"),
    # path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(),name="password_reset_done"),
    # path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    # path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete"),

    path('clients/', views.clients , name='clients'),
    path('sendnotification/<str:pk>',views.sendnotification,name='sendnotification'),

    path('notifications/', views.notifications , name='notifications'),

    path('promotions/', views.promotions , name='promotions'),
    path('addpromotion/', views.addpromotion , name='addpromotion'),
    path('updatepromotion/<str:pk>/', views.updatepromotion, name='updatepromotion'),
    path('deletepromotion/<str:pk>/', views.deletepromotion, name='deletepromotion'),


    
    path('commentaire/', views.addcommentaire , name='commentaire'),

    path('download_pdf/<int:pk>/', download_pdf, name='download_pdf'),
]

app1/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator, MaxLengthValidator, MinValueValidator, MaxValueValidator

# Create your models here.

class Client(models.Model):
    fk_user = models.OneToOneField(User, on_delete=models.CASCADE)
    GENDER_CHOICES =[
        ('F','Female'),
        ('M','Male')
    ]
    sexe = models.CharField(choices=GENDER_CHOICES,max_length=1)
    telephone = models.IntegerField(
    #    validators=[  
        # MinLengthValidator(9),
        # MaxLengthValidator(15)
        # ]
    )
    adresse = models.CharField(max_length=100)
    client_image = models.ImageField(default = "profilepic.png",null=True , blank=True)
    def __str__(self) : 
     return self.fk_user.username

class Categorie(models.Model):
    nom = models.TextField(max_length=100)
    description = models.TextField(max_length=500, blank=True, null=True)
    categorie_image = models.ImageField(default = "voyagepic.png",null=True , blank=True)
    def __str__(self) : 
     return self.nom

class Promotion(models.Model):
    titre = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    pourcentage_reduction = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])


    def _str_(self):
        return self.titre


class Hotel(models.Model):
    nom = models.TextField(max_length=100)
    NBR_ETOILE = [
        (1, '⭐'),
        (2, '⭐⭐'),
        (3, '⭐⭐⭐'),
        (4, '⭐⭐⭐⭐'),
        (5, '⭐⭐⭐⭐⭐'),
    ]
    nbr_etoiles = models.IntegerField(choices=NBR_ETOILE, null=False, blank=False)
    nbr_chambres = models.IntegerField(null=False, blank=False)
    hotel_image = models.ImageField(default = "hotel.jpeg",null=True , blank=True)
    def __str__(self):
        return self.nom


class Vol(models.Model) : 
    id = models.AutoField(primary_key=True) 
    titre = models.CharField(max_length=100,default='titre1')
    date_depart = models.DateField(null=False , blank=False)
    date_arrive = models.DateField(null=False,blank=False)
    compagnie = models.CharField(null=False , blank=False , max_length=100)
    CLASSE_CHOICES =[
        ('eco','economie'),
        ('bsn','bisness')
    ]
    classe = models.CharField(choices=CLASSE_CHOICES,null=False, blank=False ,max_length=100)
    escale = models.CharField(max_length=100 ,null=False , blank=False)
    ville_arrive = models.CharField(max_length=100 ,null=False , blank=False)
    ville_depart = models.CharField(max_length=100 ,null=False , blank=False)
    nbr_heure = models.IntegerField(null=False, blank=False)
    
    def __str__(self) : 
        return self.titre



class Voyage(models.Model):
    titre = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    date_depart = models.DateField()
    date_arrivee = models.DateField() 
    prix = models.IntegerField(null=False, blank=False)#🚩here can be blank because it's only admin tasks , it can be that the admin dont know yet the price of the voyage
    nbr_places = models.IntegerField(null=False, blank=False)  #7ydt validators 7it daro liya mochkil
    image_voyage = models.ImageField(default = "voyagepic.png",null=True , blank=True)
    categorie = models.ForeignKey('Categorie', on_delete=models.CASCADE )
    promotion = models.ForeignKey('Promotion', null=True,blank=True, on_delete=models.CASCADE)
    vol = models.ForeignKey('Vol',on_delete=models.CASCADE)
    hotel = models.ForeignKey('Hotel',on_delete=models.CASCADE)
    def __str__(self) : 
     return self.titre
    
    def getShortInfo(self):
        return self.description[:30]+"..."

class Client_voyage(models.Model):
    fk_client = models.ForeignKey(Client, on_delete=models.CASCADE)
    fk_voyage = models.ForeignKey(Voyage, on_delete=models.CASCADE)
    date_reservation = models.DateField()
    amountPaid = models.IntegerField(null=False, blank=False,default=0)
    paymentStatus = models.BooleanField(default=False)


class Adminstrateur(models.Model):
    fk_user = models.OneToOneField(User, on_delete=models.CASCADE)
    GENDER_CHOICES =[
        ('F','Female'),
        ('M','Male')
    ]
    sexe = models.CharField(choices=GENDER_CHOICES,max_length=1)
    
    def __str__(self) : 
     return self.fk_user.username



class Notification(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    adminstrateur = models.ForeignKey(Adminstrateur, on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.adminstrateur.fk_user.username} to {self.client.fk_user.username}: {self.message}"

class Commentaire(models.Model) : 
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    commentaire = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def _str_(self):
        return f"{self.client.fk_user.username}: {self.commentaire} at : {self.timestamp}"

app1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Client , Adminstrateur , Voyage , Categorie , Hotel , Vol , Notification  , Promotion , Commentaire
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import Group
from django.forms import ModelForm

class ClientRegistrationForm(UserCreationForm):
    GENDER_CHOICES = [
        ('F', 'Female'),
        ('M', 'Male')
    ]

    sexe = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect)
    telephone = forms.IntegerField(
        # validators=[MinValueValidator(7), MaxValueValidator(15)]
    )
    adresse = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ['username', 'email','password1', 'password2', 'sexe', 'telephone', 'adresse']

    def save(self, commit=True): #had method an3yto liha f register view
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()

            # Create a Client instance and associate it with the user
            client = Client.objects.create(
                fk_user=user,  # Use fk_user to associate with the User model
                sexe=self.cleaned_data['sexe'],
                telephone=self.cleaned_data['telephone'],
                adresse=self.cleaned_data['adresse'],
            )
        
        #hna kan associer user l group 'client'
        client_group = Group.objects.get(name='client')
        user.groups.add(client_group)
        return user






class AdminstrateurRegistrationForm(UserCreationForm):
    
    GENDER_CHOICES = [
        ('F', 'Female'),
        ('M', 'Male')
    ]

    sexe = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect)
    
    class Meta:
        model = User
        fields = ['username', 'email','password1', 'password2', 'sexe']
    
    def save(self, commit=True): #had method an3yto liha f register view
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            
            user.is_staff = True
            user.is_superuser = True
            user.save()

            # Create an administrateur instance and associate it with the user
            administrateur = Adminstrateur.objects.create(
                fk_user=user,  # Use fk_user to associate with the User model
                sexe =self.cleaned_data['sexe'],
            )
        
        #hna kan associer user l group 'client'
        administrateur_group = Group.objects.get(name='admin')
        user.groups.add(administrateur_group)
        return user


class ClientSettingsForm(ModelForm):
	class Meta:
		model = Client
		fields = '__all__'
		exclude = ['fk_user']

class VoyageForm(ModelForm) : 
  class Meta :
    model = Voyage
    fields = '__all__'

class categorieForm(ModelForm) : 
  class Meta :
    model = Categorie
    fields = '__all__'

class hotelForm(ModelForm) : 
  class Meta :
    model = Hotel
    fields = '__all__'

class volForm(ModelForm) : 
  class Meta :
    model = Vol
    fields = '__all__'



class notificationForm(ModelForm) : 
  class Meta :
    model = Notification
    fields = '__all__'

    widgets = {
                'client': forms.TextInput(attrs={'readonly': 'readonly'}),
                'adminstrateur':forms.TextInput(attrs={'readonly': 'readonly'}),
            }


class promotionForm(ModelForm) : 
  class Meta :
    model = Promotion
    fields = '__all__'



class commentaireForm(ModelForm) : 
  class Meta :
    model = Commentaire
    fields = '__all__'
    widgets = {
            'client': forms.TextInput(attrs={'readonly': 'readonly'}),
        }

app1/templates/app1/ClientSettings.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>DirEngine </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% comment %} <link rel="stylesheet" href="{% static '/css/main.css'%}"> {% endcomment %}
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Alex+Brush" rel="stylesheet">
  
    <link rel="stylesheet" href="{% static '/css/open-iconic-bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static '/css/animate.css'%}">
  
    <link rel="stylesheet" href="{% static '/css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static '/css/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{% static '/css/magnific-popup.css'%}">
  
    <link rel="stylesheet" href="{% static '/css/aos.css'%}">
  
    <link rel="stylesheet" href="{% static '/css/ionicons.min.css'%}">
  
    <link rel="stylesheet" href="{% static '/css/bootstrap-datepicker.css'%}">
    <link rel="stylesheet" href="{% static '/css/jquery.timepicker.css'%}">
  
  
  <link rel="stylesheet" href="{% static '/css/flaticon.css'%}">
  <link rel="stylesheet" href="{% static '/css/icomoon.css'%}">
  <link rel="stylesheet" href="{% static '/css/style.css'%}">

  <style>
    .card {
      border-radius: 20px;
      background-color: #e6eaee;
      box-shadow: 10px 10px 5px #888888;
    }

 

    .card-img-top {
      border-radius: 20px;
      padding: 10px;
    }

    .card-text{
      font-size: 15px;
      color: black;
    }

    .field-value {
      font-weight: bold;
      color: black; /* Adjust the color as needed */
      /* Add more styling as needed */
    }
    img.profile-pic{
        position: relative;
        top: -100px;
        border: 1px solid;
        width: 200px;
        height:200px;
        margin: 0 auto;
        border-radius: 50%;

    }
    div.card h3{
        position: relative;
        top: -50px;
        text-align: center;
    }
  </style>
  
  <!--My css-->
  <link rel="stylesheet" href="{% static '/css/Mycss.css'%}">
  <!--My js-->
  <script src="{% static 'js/Myjs.js' %}"></script>
  </head>
  <body>
    
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home'  %}">Reservo.</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
      </button>

      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><a href="{% url 'home' %}" class="nav-link">Home</a></li>
        {% if not user.is_authenticated %}
            <li class="nav-item cta"><a href="{% url 'login' %}" class="nav-link"><span>Se connecter</span></a></li>
        {% else %}
            <li class="nav-item cta"><a href="{% url 'logout' %}" class="nav-link"><span>Se déconnecter</span></a></li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>
    <!-- END nav -->
    <div class="container" style="padding-top : 50px">
			<div class="col-md-12 mx-auto">
				<div class="card card-body">
					<form method="POST" action="" enctype="multipart/form-data">
						{% csrf_token %}
		
						<div class="form-group row">
							<label for="id_titre" class="col-sm-2 col-form-label">Sexe:</label>
							<div class="col-sm-4">{{form.sexe}}</div>
		
							<label for="id_prix" class="col-sm-2 col-form-label">Telephone:</label>
							<div class="col-sm-4">{{form.telephone}}</div>
						</div>
						<div class="form-group row">
							<label for="id_titre" class="col-sm-2 col-form-label">Adresse:</label>
							<div class="col-sm-4">{{form.adresse}}</div>
							<label for="id_titre" class="col-sm-2 col-form-label">Image: de profil</label>
							<div class="col-sm-4">{{form.client_image}}</div>
						</div>
						<div class="d-flex justify-content-center mb-3">
							<input class="btn btn-primary" type="submit" name="add" />
						</div>
					</form>
				</div>
		
				{% if form.errors %}
				<p class="text-danger">Form has errors: {{ form.errors }}</p>
				{% endif %}
			</div>
		</div>


	
	

    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <script src="{% static  'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'js/google-map.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  <script>
	var input = document.getElementById('checkin_date');

	// Initialize the date picker
	{% comment %} $(document).ready(function(){
		$('#checkin_date').datepicker({
			format: 'mm/dd/yyyy', // set the format of the date picker if needed
			autoclose: true,
			todayHighlight: true
		});
	}); {% endcomment %}
	input.addEventListener('change', function() {
		// Get the selected date from the input field
		var selectedDate = input.value;
		
		// Log the selected date to the console (you can replace this with any other action you want)
		console.log('Selected date:', selectedDate);
	});
  <script>

    
  </body>
</html>

app1/templates/app1/addcategorie.html
{% extends 'app1/mainAdmin.html' %}

{% block content %}
<div class="container">
  <div class="col-md-12 mx-auto">
    <div class="card card-body">
      
      <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group row">
          <label for="id_titre" class="col-sm-2 col-form-label">Titre:</label>
          <div class="col-sm-4">{{form.nom}}</div>

          <label for="id_prix" class="col-sm-2 col-form-label">Description:</label>
          <div class="col-sm-4">{{form.description}}</div>
        </div>
        <div class="form-group row">
          <label for="id_titre" class="col-sm-2 col-form-label">categorie image:</label>
          <div class="col-sm-4">{{form.categorie_image}}</div>
        </div>
       
        <div class="d-flex justify-content-center mb-3">
          <input class="btn btn-primary" type="submit" name="add">
        </div>
        
      </form>
    </div>

    {% if form.errors %}
      <p class="text-danger">Form has errors: {{ form.errors }}</p>
    {% endif %}
  </div>
</div>
{% endblock content %}

app1/templates/app1/addvoyage.html
{% extends 'app1/mainAdmin.html' %}

{% block content %}
<div class="container">
  <div class="col-md-12 mx-auto">
    <div class="card card-body">
      
      <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group row">
          <label for="id_titre" class="col-sm-2 col-form-label">Titre:</label>
          <div class="col-sm-4">{{form.titre}}</div>

          <label for="id_prix" class="col-sm-2 col-form-label">Prix:</label>
          <div class="col-sm-4">{{form.prix}}</div>
        </div>

        <div class="form-group row">
          <label for="id_date_depart" class="col-sm-2 col-form-label">Date de depart:</label>
          <div class="col-sm-4">{{form.date_depart}}</div>

          <label for="id_date_arrivee" class="col-sm-2 col-form-label">Date d'arrive:</label>
          <div class="col-sm-4">{{form.date_arrivee}}</div>
        </div>

        <div class="form-group row">
          <label for="id_nbr_places" class="col-sm-2 col-form-label">Number of Places:</label>
          <div class="col-sm-4">{{form.nbr_places}}</div>

          <label for="id_image_voyage" class="col-sm-2 col-form-label">Image:</label>
          <div class="col-sm-4">{{form.image_voyage}}</div>
        </div>

        <div class="form-group row">
          <label for="id_categorie" class="col-sm-2 col-form-label">Category:</label>
          <div class="col-sm-4">{{form.categorie}}</div>

          <label for="id_vol" class="col-sm-2 col-form-label">Vol:</label>
          <div class="col-sm-4">{{form.vol}}</div>
        </div>

        <div class="form-group row">
          <label for="id_hotel" class="col-sm-2 col-form-label">Hotel:</label>
          <div class="col-sm-4">{{form.hotel}}</div>

          <label for="id_description" class="col-sm-2 col-form-label">Promotion:</label>
          <div class="col-sm-4">{{form.promotion}}</div>
        </div>

        <div class="form-group row">

          <label for="id_description" class="col-sm-2 col-form-label">Description:</label>
          <div class="col-sm-4">{{form.description}}</div>
        </div>

        <div class="d-flex justify-content-center mb-3">
          <input class="btn btn-primary" type="submit" name="add">
        </div>
        
      </form>
    </div>

    {% if form.errors %}
      <p class="text-danger">Form has errors: {{ form.errors }}</p>
    {% endif %}
  </div>
</div>
{% endblock content %}

app1/templates/app1/deletepromotion.html
{% extends 'app1/mainAdmin.html' %} {% block content %}
<div class="container">
  <div class="col-md-12 mx-auto">
    <div class="card card-body text-center">
      <p>Are you sure you want to delete "{{item}}"?</p>
      <form action="{% url 'deletepromotion' item.id %}" method="POST">
        {% csrf_token %}
        <a class="btn btn-warning" href="{% url 'promotions' %}">cancel</a>
        <input class="btn btn-danger" type="submit" name="confirm" />
      </form>
    </div>
  </div>
</div>
{% endblock content %}

app1/templates/app1/reservation_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>La Facture</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container" >
        <h1>Identifiant de Réservation : {{ res_id }}</h1>

        <div class="row">
            <div class="col-md-6">
                <h2>Informations sur le Client</h2>
                <p>Nom du Client : {{ client.fk_user.username }}</p>
                <p>Email du Client : {{ client.fk_user.email }}</p>
                <p>Genre du Client : {{ client.get_sexe_display }}</p>
                <p>Téléphone du Client : {{ client.telephone }}</p>
                <p>Adresse du Client : {{ client.adresse }}</p>
                <p>CIN du Client : {{ client.CIN }}</p>
            </div>
            <div class="col-md-6">
                <h2>Informations sur le Voyage</h2>
                <h3>Informations de Réservation pour l'ID du Voyage : {{ voyage.id }}</h3>
                <p>Description du Voyage : {{ voyage.description }}</p>
                <p>Montant Payé : {{ voyage.prix }}</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <h2>Informations sur l'Hôtel</h2>
                <p>Nom de l'Hôtel : {{ hotel.nom }}</p>
                <p>Étoiles de l'Hôtel : {{ hotel.nbr_etoiles }}</p> 
            </div>
            <div class="col-md-6">
                <h2>Informations sur le Vol</h2>
                <p>Titre du Vol : {{ vol.titre }}</p>
                <p>Date de Départ : {{ vol.date_depart }}</p>
                <p>Date d'Arrivée : {{ vol.date_arrive }}</p>
                <p>Compagnie : {{ vol.compagnie }}</p>
                <p>Classe : {{ vol.get_classe_display }}</p>
                <p>Escales : {{ vol.escale }}</p>
                <p>Ville de Départ : {{ vol.ville_depart }}</p>
                <p>Ville d'Arrivée : {{ vol.ville_arrive }}</p>
                <p>Durée (heures) : {{ vol.nbr_heure }}</p>
            </div>
        </div>
    </div>
</body>
</html>

app1/templates/app1/sendnotification.html
{% extends 'app1/mainAdmin.html' %} {% block content %}
<style>
.fd{
  display: none;
}
</style>
<div class="container">
  <div class="col-md-12 mx-auto">
    <div class="card card-body">
      <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group row">
          <div class="fd">{{form.adminstrateur}}</div>


          <div class="fd">{{form.client}}</div>
        </div>
         <div class="form-group row">
          <label for="id_titre" class="col-sm-2 col-form-label">Message:</label>
          <div class="col-sm-4">{{form.message}}</div>
        </div>

      <div class="d-flex justify-content-center mb-3">
        <input class="btn btn-primary" type="submit" name="send">
      </div>
      
      </form>
    </div>

    {% if form.errors %}
    <p class="text-danger">Form has errors: {{ form.errors }}</p>
    {% endif %}
  </div>
</div>
{% endblock content %}